version: "3"

services:
  proxy:
    image: nginx:mainline-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:8000

  frontend:
    build:
      context: frontend

  api: &backend
    build:
      context: backend
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_DEBUG: $DJANGO_DEBUG
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_CORS_ALLOW_ALL_ORIGINS: $DJANGO_CORS_ALLOW_ALL_ORIGINS

      DATABASE_NAME: $DATABASE_NAME
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT

      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
      CELERY_RESULT_EXPIRES: $CELERY_RESULT_EXPIRES
    ports:
      - 8001:8000

  worker:
    <<: *backend
    ports: []
    command:
      - "-c"
      - "celery -A config worker -l info"

  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: nmap

  redis:
    image: redis:6.0-alpine

volumes:
  pg_data: {}
