# Generated by Django 3.1.5 on 2021-01-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True, verbose_name='Scan ID')),
                ('host', models.CharField(max_length=50, verbose_name='Host Value')),
                ('state', models.CharField(choices=[('PENDING', 'waiting for execution or unknown task id'), ('STARTED', 'task has been started'), ('SUCCESS', 'task executed successfully'), ('FAILURE', 'task execution resulted in exception'), ('RETRY', 'task is being retried'), ('REVOKED', 'task has been revoked')], default='PENDING', max_length=8, verbose_name='Scan Status')),
                ('output', models.TextField(verbose_name='Scan Output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
